Feat/sc group clustering
Taraxa-project/echo pull request #114
Opened 2023-05-17 12:49 UTC by guibvieira

Revamp the smart contract implementation from ingester cluster centric to group cluster centric. This has significant improvements from the previous implementation to the current implementation. 

Previous implementation using ingester cluster centric approach Gas Report: 

<img width="479" alt="image" src="https://github.com/Taraxa-project/echo/assets/33320349/424cc482-ade3-49f5-91eb-a9f27a86c7ac">

Current Implementation with group cluster centric approach gas report:

<img width="918" alt="image" src="https://github.com/Taraxa-project/echo/assets/33320349/868a8df6-a245-4316-a9a2-2202308c7cdf">

Details of smart contract implementation: 

https://docs.google.com/document/d/145UzXkKSRs2JhWHxFTShlT1HvuV1thDUW7ABYeVyLsA/edit#

2023-05-19 13:03 UTC, stefanizota commented on smart-contracts/contracts/facets/RegistryFacet.sol
>      function unRegisterIngester(address ingesterAddress) external onlyRegisteredController {
For the final swapping part (removing from `s.controllerToIngesters[controllerAddress]`), maybe a little cleaner: 

- if this is not the last ingester and ingester count > 1 then swap;
- pop, revoke ingester role, etc...
- if ingester count is 0 revoke controller role, etc..

2023-05-19 14:25 UTC, guibvieira commented on smart-contracts/contracts/facets/RegistryFacet.sol
>          uint256 ingesterIndexToRemove = s.ingesterToController[ingesterAddress].ingesterIndex;
Thank you for spotting this! I was updating the wrong index in the swapping. Have fixed it now so it is updating ingesterIndex correctly instead of updating ingesterAddressesIndex.

2023-05-19 14:25 UTC, guibvieira commented on smart-contracts/contracts/facets/RegistryFacet.sol
>      function unRegisterIngester(address ingesterAddress) external onlyRegisteredController {
Yes looks cleaner thank you. Have re-structured it now

2023-05-22 08:40 UTC, stefanizota commented on smart-contracts/contracts/facets/RegistryFacet.sol
>          uint numIngestersPerController = s.controllerToIngesters[controllerAddress].length;
Maybe move the following before checking the length (`delete s.ingesterToController[ingesterAddress]` can be moved in the function `removeIngesterFromControllerMapping` and we're left with only revoking the ingester role):
```
 _revokeRole("INGESTER_ROLE", ingesterAddress);
delete s.ingesterToController[ingesterAddress];
```
Then check if length is 0 to remove the controller role, etc.
And finally, remove the ingester from cluster.

2023-05-22 09:47 UTC, guibvieira commented on smart-contracts/contracts/facets/RegistryFacet.sol
>          uint numIngestersPerController = s.controllerToIngesters[controllerAddress].length;
Nice, this simplifies it even more. I have pushed it now, but created a new function removeIngesterFromIngesterMapping where I do both the revoke ingester and removal of ingester key. Wasn't too sure about including the removal of ingester mapping in the removeIngesterFromControllerMapping function. The naming didn't make too much sense to include it in there. Let me know what you think about this, happy to change

2023-05-23 17:23 UTC, VargaElod23 requested changes
We'll need to add the autodoc deps too and some gas econ on iterations but besides that looks phenomenal 🔥

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/facets/CommonFunctionsFacet.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
```suggestion
        for (uint256 i = 0; i < s.clusterIds.length; ) {
        ...
        unchecked {
         ++i
         }
```
Also, since we have a relatively small amount of clusterIds we don't need to be aware of integer safety checks

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/facets/CommonFunctionsFacet.sol
> +                for ( uint256 j = 0; j < groupsLength; j++) {
Same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/facets/CommonFunctionsFacet.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/facets/CommonFunctionsFacet.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/facets/CommonFunctionsFacet.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/test/facets/CommonFunctionsFacetTest.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/test/facets/CommonFunctionsFacetTest.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/test/facets/CommonFunctionsFacetTest.sol
> +                for ( uint256 j = 0; j < groupsLength; j++) {
same thing applies

2023-05-23 17:23 UTC, VargaElod23 commented on smart-contracts/contracts/test/facets/CommonFunctionsFacetTest.sol
> +            if (s.groupsCluster[s.clusterIds[i]].isActive) {
basically everywhere where you have very clearly not overflowing iterators(few iterations)

2023-05-24 08:10 UTC, stefanizota commented on smart-contracts/contracts/interfaces/IIngesterRegistration.sol
>          bool verified;
What is `verified` for? I don't see it used. Maybe we can remove it?

2023-05-24 09:48 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
>      uint256 ingesterCount;
Do we need `ingesterCount`? The length of an dynamic array is already stored.

2023-05-24 13:50 UTC, VargaElod23 commented on smart-contracts/contracts/facets/AccessControlFacet.sol
Also, is there any reasoning behind why we use  `@solidstate` here instead of the simple AccessControl from OZ?

2023-05-24 15:28 UTC, guibvieira commented on smart-contracts/contracts/facets/AccessControlFacet.sol
Because OZ does not support open zeppelin, it's recommended to use solidstate implementation as they do support it and it has been tested against it. Read that here: https://ethereum.stackexchange.com/questions/139470/how-to-handle-constructor-and-access-control-system-using-oz-library-in-diamond

2023-05-24 15:48 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +    uint256[] inActiveClusters;
👍

2023-05-24 15:50 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +    mapping(uint => IIngesterGroupManager.GroupsCluster) groupsCluster;
👍

2023-05-24 15:58 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
I chose not to use delete here because it's generally not recommended to use it in solidity. In this scenario here, it is guaranteed that at some point any new groups would be added back in and I found that it would be simpler to keep the cluster, so the clusterIds remain incremental and everything is more consistent. It also avoiding clusterId iterations when adding groups back in when there unallocatedClusters available. 
At least this is what I read when researching about this topic. But would be interesting hear you opinion on this @VargaElod23

2023-05-24 16:23 UTC, guibvieira commented on smart-contracts/contracts/interfaces/IIngesterRegistration.sol
>          bool verified;
Yes, 100%. This was to just make sure that we could check if an ingester was registered, but that is taken care of by the require checks we do when requesting an ingester anyway. Will remove

2023-05-24 16:36 UTC, guibvieira commented on smart-contracts/contracts/facets/RegistryFacet.sol
> +        Ingester memory ingester = IIngesterRegistration.Ingester(ingesterAddress, true, false, 0);
I believe that taking that approach would require me to do: 

```
s.controllerToIngesters[controllerAddress].push();
Ingester storage ingester = s.controllerToIngesters[controllerAddress][s.controllerToIngesters[controllerAddress].length - 1];
ingester.ingesterAddress = ingesterAddress;
```

However, I think readibility here is worse. What do you think about the following instead? 

```
s.controllerToIngesters[controllerAddress].push(Ingester({
    ingesterAddress: ingesterAddress,
    isAllocated: false,
    clusterId: 0
}));
```

2023-05-24 16:38 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
>      uint256 ingesterCount;
Nope, I agree we don't need it. Will remove

2023-05-24 17:22 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
>      uint256 groupCount;
No, substituted with groupUsernames.length instead

2023-05-24 17:23 UTC, guibvieira commented on smart-contracts/contracts/interfaces/IIngesterGroupManager.sol
> +        uint256 groupCount;
Nope, I have removed this as well. Thanks!

2023-05-24 18:03 UTC, VargaElod23 commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
Technically speaking `delete` only returns some gas to user and assigns defaults... I think you can use it without any second thoughts.

2023-05-24 18:04 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
Same for you @Malak67 :) 🙏🏻

2023-05-24 18:07 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +    function removeGroupFromCluster(uint256 clusterId, string memory groupUsername) internal {
Ah nice, thanks! I missed this, I have done the same for removeGroupFromGroupUsernames(), also does not need it

2023-05-24 18:14 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
Ok. In that case, I will use delete and remove the need for the concept of `inactiveClusters` . This will also simplify addGroupToCluster as you mentioned below @stefanizota

2023-05-24 18:27 UTC, stefanizota commented on smart-contracts/contracts/facets/RegistryFacet.sol
> +        Ingester memory ingester = IIngesterRegistration.Ingester(ingesterAddress, true, false, 0);
https://docs.soliditylang.org/en/latest/types.html#array-members

2023-05-25 09:27 UTC, stefanizota commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
It has the same effect in the end. `delete` looks clearer and it's probably cheaper.

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +                    IIngesterRegistration.Ingester[] memory controllerIngesters = s.controllerToIngesters[controllerAddress];
We can change to `storage` to prevent a copy.

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +                            if (currentCluster.ingesterAddresses[j] == controllerIngesters[k].ingesterAddress && currentCluster.ingesterAddresses[j] != ingesterAddress) {
`currentCluster.ingesterAddresses[j] != ingesterAddress` can this ever happen?

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +                ingesterIndexToRemove = i;
Not used. We can remove this and the initialisation.

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +            s.groupsCluster[clusterId].ingesterAddresses.push(ingesterAddress);
Is not this the same functionality as the function `addIngesterToClusterId`?

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +                        address unAllocatedIngester = s.unAllocatedIngesters[s.unAllocatedIngesters.length - 1];
There's no check for controller address (another ingester with the same controller).

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +    function removeIngesterFromCluster(address ingesterAddress, uint256 clusterId) internal {
First check if it is unallocated and remove it from the `s.unAllocatedIngesters`.

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +        addIngesterToClusterId(ingesterAddressToMove, assignClusterId);
There's no check for controller address (another ingester with the same controller).

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +    function getClusterWithIngesterReplication() internal view returns(uint256, bool) {
Maybe find a cluster with most replicas.

2023-05-25 10:49 UTC, stefanizota commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +        checkUnallocatedIngesters(clusterId);
We only need this if we just created a new cluster. Also we can allocate more than one unallocated ingester to this new cluster (keep the controller address restriction in mind).

2023-05-25 10:52 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
When trying to implement this - removing inactiveClusters concept - I found that we would end up with an incositent clusterIds array. For example if I have clusterIds [0,1,2] and remove clusterId 0, end up with clusterIds [2,1]. When adding a new cluster now I would have to keep create a clusterId counter and always increment up whether clusterIds have been removed or not. This will result in cluderIds of potential alternate numbers, e.g. [2,1,4,6,7]. This can work ofc but it feels to me that having the inactive clusters would make it more simple and keep the incremental consistency of clusterIds. If clusterId gets removed, it becomes inactive, clusterIds [0 (inactive), 1,2] and when new groups are added back in, then the order is maintained and simply actives clusterId 0. Let me know what you think @stefanizota

2023-05-25 10:55 UTC, VargaElod23 commented on smart-contracts/contracts/facets/CommonFunctionsFacet.sol
> +        for (uint256 i = 0; i < s.clusterIds.length; i++) {
yeah, if it doesn't destroy readability

2023-05-25 11:10 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +        for (uint256 i = 0; i < numClusters; i++) {
This only finds the minimum. And if the cluster(s) have already an ingester with the same controller we do nothing. We should probably sort ascending by the ingester count and try each cluster.
To simplify the restriction of one owner per cluster we can keep a mapping with the controller ingester for cluster. We can then replace the next for loops with a simple mapping check.

2023-05-25 11:21 UTC, stefanizota commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
I did mention anything about removing the inactive clusters and I did not think at an alternative.

I just prefer
`delete s.groupsCluster[clusterId].ingesterAddresses;`
vs 
`s.groupsCluster[clusterId].ingesterAddresses = new address[](0);`
but the effect is the same.

2023-05-25 14:55 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +                            if (currentCluster.ingesterAddresses[j] == controllerIngesters[k].ingesterAddress && currentCluster.ingesterAddresses[j] != ingesterAddress) {
No, this second check does not make sense, this could never happen. Removed

2023-05-25 15:03 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +                        address unAllocatedIngester = s.unAllocatedIngesters[s.unAllocatedIngesters.length - 1];
This scenario is only run when there is no ingester addresses left in the cluster, so the unallocated ingester will be the only one assigned to this cluster, would not be possible to clash with another controller. Don't think the check is needed here

2023-05-25 15:11 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +            s.groupsCluster[clusterId].ingesterAddresses = new address[](0);
Oh ok! misundestood what you said, made that change now

2023-05-25 15:23 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +    function removeIngesterFromCluster(address ingesterAddress, uint256 clusterId) internal {
Sorry not sure if I fully understand this one. Are you proposing to check if there are unallocatedIngesters before doing the check to see if the cluster is empty after removing the desired ingester from cluster? 

Something like this? 
```
emit IngesterRemovedFromCluster(clusterId, ingesterAddress);

                //check if there is unallocated ingesters to assign
                if (s.unAllocatedIngesters.length > 0) {
                    address unAllocatedIngester = s.unAllocatedIngesters[s.unAllocatedIngesters.length - 1];
                    s.unAllocatedIngesters.pop();
                    addIngesterToClusterId(unAllocatedIngester, clusterId);
                }
                else if (s.groupsCluster[clusterId].ingesterAddresses.length == 0) {
                    
                    if (s.maxIngestersPerGroup > 1) {
                        (uint clusterIdAvailable, bool foundAvailableCluster) = getClusterWithIngesterReplication();
                        //if available cluster, then steal ingester from available cluster and put it into empty cluster
                        if (foundAvailableCluster) {
                            fetchIngesterFromAvailableCluster(clusterIdAvailable, clusterId);
                        } else {
                            emit ClusterHasNoIngesters(clusterId);
                        }
                    } else {
                        emit ClusterHasNoIngesters(clusterId);
                    }
                } 
                break;
                ```

2023-05-25 17:54 UTC, guibvieira commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +        for (uint256 i = 0; i < numClusters; i++) {
Thanks for spotting this! I've re-written the function. I am now sorting the clusterIds ( I keep this in memory and not modify storage otherwise I would have to be swapping indices everywhere and think that is a bit more complex ), I then take the first element of the sorted clusterIds and have an isolated function to check whether there is the same controller or not. I ended up not adding an additional mapping as the array to iterate over will always be quite small. Happy to change this, let me know if you think this is better or if you feel like It would be better to use the mapping or a different approach :)

2023-05-26 07:41 UTC, VargaElod23 commented on smart-contracts/contracts/facets/RegistryFacet.sol
>  import "../interfaces/IIngesterRegistration.sol";
Here we don't need bot the `@solidstate/AccessControl` and the `AccessControlFacet` imports

2023-05-26 07:51 UTC, VargaElod23 commented on smart-contracts/contracts/test/libraries/LibAppStorageUpgradeTest.sol
>      bytes32 internal constant INGESTER_ROLE = keccak256("INGESTER_ROLE");
```suggestion
    bytes32 internal constant _INGESTER_ROLE = keccak256("INGESTER_ROLE");
```
per naming conv

2023-05-26 07:52 UTC, VargaElod23 commented on smart-contracts/contracts/test/libraries/LibAppStorageUpgradeTest.sol
>      bytes32 internal constant INGESTER_ROLE = keccak256("INGESTER_ROLE");
same for below

2023-05-26 11:03 UTC, guibvieira commented on smart-contracts/contracts/facets/GroupManagerFacet.sol
> +        checkUnallocatedIngesters(clusterId);
Added the check to only run when a new cluster is added. Also modified checkUnallocatedIngesters to allocated as many ingesters as available (within cluster constraints) and also to the controller address check

2023-05-26 11:05 UTC, guibvieira commented on smart-contracts/contracts/facets/RegistryFacet.sol
>  import "../interfaces/IIngesterRegistration.sol";
I removed the `@solidstate/AccessControl` import but still need the AccessControlFacet to be able to inherit it's functionality to grantRole and to have access to the modifiers

2023-05-29 10:08 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +    function removeIngesterFromCluster(address ingesterAddress, uint256 clusterId) internal {
What I meant is that the ingester may be unallocated. So you have to remove it from that list.

2023-05-29 10:09 UTC, stefanizota commented on smart-contracts/contracts/libraries/LibAppStorage.sol
> +        addIngesterToClusterId(ingesterAddressToMove, assignClusterId);
Ok.

2023-06-14 08:45 UTC, merged